<a href="https://colab.research.google.com/github/shivanibandi110/Sudoku-solver/blob/main/GDSC_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#GDSC-day1

In [ ]:
import numpy as np


In [ ]:
list1 = [1,2,3,4]

In [ ]:
print(list1)

[1, 2, 3, 4]


In [ ]:
array = np.array([list1,list1])
print(array)

[[1 2 3 4]
 [1 2 3 4]]


In [ ]:
type(array)

numpy.ndarray

In [ ]:
import pandas as pd

In [ ]:
ages = np.array([4,5,11,9])
series = pd.Series(ages,index=['Emma','math','tom','jerry'])

In [ ]:
series

Emma      4
math      5
tom      11
jerry     9
dtype: int64

In [ ]:
dataf = pd.DataFrame([
                       ['Arjun' , 36 , 'Bleak street','34'],
                       ['Sam' , 29 , 'Bleak street 2','19']
], columns= ['name','age', 'address','rollno'])

In [ ]:
dataf

name  age         address rollno
0  Arjun   36    Bleak street     34
1    Sam   29  Bleak street 2     19

In [ ]:
dataf.set_index('name')

age         address rollno
name                             
Arjun   36    Bleak street     34
Sam     29  Bleak street 2     19

In [ ]:
from numpy import exp, array, random, dot

In [ ]:
class NeuralNetwork():
  def __init__(self):
    random.seed(1)
    self.synaptic_weights = 2 * random.random((3,1))-1 # initializing weights

  def __sigmoid(self, x):
    return 1/(1+exp(-x))      #activation of neuron

  def __sigmoid_derivative(self, x):
    return x*(1-x)

  def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
    for iteration in range(number_of_training_iterations):
      output = self.think(training_set_inputs)
      error = training_set_outputs - output
      adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

      self.synaptic_weights += adjustment  #back propagation

  def think(self, inputs):
    return self.__sigmoid(dot(inputs, self.synaptic_weights))


In [ ]:
neural_network = NeuralNetwork()

In [ ]:
print(neural_network.synaptic_weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [ ]:
training_set_inputs = array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
training_set_outputs = array([[0,1,1,0]]).T

In [ ]:
neural_network.train(training_set_inputs,training_set_outputs, 10000)

In [ ]:
print(neural_network.synaptic_weights) #

[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [ ]:
print(neural_network.think(array([1,0,0])))

[0.99993704]


In [ ]:
print(neural_network.think(array([1,1,0])))

[0.9999225]


In [ ]:
print(neural_network.think(array([0,0,0])))

[0.5]
